#!/bin/bash
echo "AIRFLOW_HOME=/airflow" >> /etc/bash.bashrc
export AIRFLOW_HOME=/airflow

apt-get update -y
apt-get  install -y unzip build-essential python-dev libsasl2-dev python-pandas binutils libmysqlclient-dev mysql-client python-pip
pip install --upgrade pip
pip install MySQL-python
pip install -U boto
pip install airflow
pip install airflow[celery]
pip install airflow[mysql] 

mkdir ${AIRFLOW_HOME}
mkdir ${AIRFLOW_HOME}/dags
mkdir ${AIRFLOW_HOME}/logs
mkdir ${AIRFLOW_HOME}/plugins

cat <<EOF > ${AIRFLOW_HOME}/start-worker.sh
#!/bin/bash
nohup airflow worker $* >> ${AIRFLOW_HOME}/worker.logs &
EOF

cat <<EOF > ${AIRFLOW_HOME}/airflow.cfg
[core]
airflow_home = /airflow
dags_folder = /airflow/dags
base_log_folder = /airflow/logs
plugins_folder = /airflow/plugins
remote_base_log_folder =
remote_log_conn_id =
encrypt_s3_logs = False
s3_log_folder =
executor = CeleryExecutor
sql_alchemy_conn = mysql://airflowuser:airflowpassword@34.204.41.31:3306/airflowdb
sql_alchemy_pool_size = 5
sql_alchemy_pool_recycle = 3600
parallelism = 32
dag_concurrency = 16
dags_are_paused_at_creation = True
non_pooled_task_slot_count = 128
max_active_runs_per_dag = 16
load_examples = True
fernet_key = cryptography_not_found_storing_passwords_in_plain_text
donot_pickle = False
dagbag_import_timeout = 30
task_runner = BashTaskRunner
default_impersonation =
security =
unit_test_mode = False

[cli]
api_client = airflow.api.client.local_client
endpoint_url = http://34.204.41.31:8080

[api]
auth_backend = airflow.api.auth.backend.default
[operators]
default_owner = Airflow
default_cpus = 1
default_ram = 512
default_disk = 512
default_gpus = 0

[webserver]
base_url = http://34.204.41.31:8080
web_server_host = 0.0.0.0
web_server_port = 8080
web_server_ssl_cert =
web_server_ssl_key =
web_server_worker_timeout = 120
worker_refresh_batch_size = 1
worker_refresh_interval = 30
secret_key = temporary_key
workers = 2
worker_class = sync
access_logfile = -
error_logfile = -
expose_config = False
authenticate = False
filter_by_owner = False
owner_mode = user
dag_orientation = LR
demo_mode = False
log_fetch_timeout_sec = 5
hide_paused_dags_by_default = False

[email]
email_backend = airflow.utils.email.send_email_smtp

[smtp]
smtp_host = localhost
smtp_starttls = True
smtp_ssl = False
smtp_port = 25
smtp_mail_from = airflow@airflow.com

[celery]
celery_app_name = airflow.executors.celery_executor
celeryd_concurrency = 16
worker_log_server_port = 8793
broker_url = amqp://radmin:radmin@34.204.41.31/anix 
#celery_result_backend = amqp://radmin:radmin@34.204.41.31/anix 
celery_result_backend = db+mysql://airflowuser:airflowpassword@34.204.41.31:3306/anixdb
flower_host = 0.0.0.0
flower_port = 5555
default_queue = default

[scheduler]
job_heartbeat_sec = 5
scheduler_heartbeat_sec = 5
run_duration = -1
min_file_process_interval = 0
dag_dir_list_interval = 300
print_stats_interval = 30
child_process_log_directory = /airflow/logs/scheduler
scheduler_zombie_task_threshold = 300
catchup_by_default = True
statsd_on = False
statsd_host = localhost
statsd_port = 8125
statsd_prefix = airflow
max_threads = 2
authenticate = False

[mesos]
master = localhost:5050
framework_name = Airflow
task_cpu = 1
task_memory = 256
checkpoint = False
authenticate = False

[kerberos]
ccache = /tmp/airflow_krb5_ccache
principal = airflow
reinit_frequency = 3600
kinit_path = kinit
keytab = airflow.keytab
[github_enterprise]
api_rev = v3

[admin]
hide_sensitive_variable_fields = True
EOF

sh ${AIRFLOW_HOME}/start-worker.sh

#webserver:8080
#mysql-server:3306
#rabbitmq-server:5672 15672
#flower:5555
