#!/bin/bash

#rabbitmq-server

apt-get update -y
apt-get install -y rabbitmq-server

gunzip /usr/share/doc/rabbitmq-server/rabbitmq.config.example.gz
cp /usr/share/doc/rabbitmq-server/rabbitmq.config.example  /etc/rabbitmq/rabbitmq.config

systemctl start rabbitmq-server 
systemctl enable rabbitmq-server

rabbitmq-plugins enable rabbitmq_management
rabbitmqctl add_user radmin radmin 
rabbitmqctl set_user_tags radmin administrator 
rabbitmqctl set_permissions -p / radmin ".*" ".*" ".*"

systemctl restart rabbitmq-server 

#executor = CeleryExecutor
#broker_url = amqp://radmin:radmin@localhost/anix 
#celery_result_backend = amqp://radmin:radmin@localhost/anix 
