#!/bin/bash

apt-get update -y
echo mysql-server mysql-server/root_password select Qwaszx!2 | debconf-set-selections
echo mysql-server mysql-server/root_password_again select Qwaszx!2 | debconf-set-selections
apt-get  install -y mysql-server rabbitmq-server

systemctl start mysql


#mysql database	    : anixdb
#mysql user 	      : airflowuser
#mysql user pass	  : airflowpassword

mysql -u root -pQwaszx12 <<MY_QUERY
CREATE DATABASE anixdb CHARACTER SET utf8 COLLATE utf8_unicode_ci;
CREATE USER 'airflowuser'@'localhost' IDENTIFIED BY 'airflowpassword';
GRANT ALL PRIVILEGES ON * . * TO 'airflowuser'@'localhost';
FLUSH PRIVILEGES;
MY_QUERY

systemctl start rabbitmq-server 
systemctl enable rabbitmq-server
rabbitmq-plugins enable rabbitmq_management
rabbitmqctl add_user radmin radmin 
rabbitmqctl set_user_tags radmin administrator 
rabbitmqctl set_permissions -p / radmin ".*" ".*" ".*"

cd ${AIRFLOW_HOME}; airflow initdb
sh ${AIRFLOW_HOME}/start-webserver.sh
sh ${AIRFLOW_HOME}/start-scheduler.sh
